version: '3'

services:
  app:
    image: golang:latest
    container_name: go-dpm
    volumes:
      - ./app:/app
    working_dir: /app
    command: go run main.go
    ports:
      - "8080:8080"  # Adjust the port to match your Go application

  postgres:
    image: postgres:latest
    container_name: postgres-dpm
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5433:5432"  # Map the container port 5432 to host port 5433

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
